### ISSUE TITLE
basic tests : the . test doesn't show results and it adds 1 false to the final count 

### ISSUE THREAD

**Issue by melobern** [mcombeau/minitester-minishell-tester#1]
The . test, [010] on this picture :
![image](https://github.com/mcombeau/minitester-minishell-tester/assets/46427692/b3b44f9f-5602-4043-a685-011ef7ef7ca7)
![image](https://github.com/mcombeau/minitester-minishell-tester/assets/46427692/653537d3-4e66-4175-a42a-a4fefd3de975)

Solution : in minishell_tests.txt, if we change . for ".",  the test goes properly :
![image](https://github.com/mcombeau/minitester-minishell-tester/assets/46427692/a9894d0f-5435-4ab1-bdfa-a625764be955)

**Comment by mcombeau** [comment]
Hey @melobern,

Thank you for pointing this issue out. For that test, the script expected minishell to have a 'command not found' or 'is a directory' error, but I didn't handle the case where minishell returned a different kind of error. 

It is now fixed in [commit 94006c6fd4bae2a0a3587daaa971b855d58772df](https://github.com/mcombeau/minitester-minishell-tester/commit/94006c6fd4bae2a0a3587daaa971b855d58772df). Now, if your minishell results in another type of error the output will correctly be displayed, such as:

![Screenshot_2024-05-23_15-57-00](https://github.com/mcombeau/minitester-minishell-tester/assets/52008667/a901094b-7ade-4e5a-99d9-3e012543a72b)

The tester still considers this an error and the test is counted as failed. For that command, '.', it still expects 'command not found' with exit code 127 or 'is a directory' with exit code 126.
